# Generated by Django 5.0.7 on 2024-08-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], null=True),
        ),
    ]
