# Generated by Django 5.0.7 on 2024-08-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserlogs',
            name='uid',
            field=models.CharField(default='khskfhskfhfh', max_length=300),
        ),
    ]
